# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model 
info:
  version: 1.4.0
  description: OAI-NSSF Release v1.4.0
configuration:
  nsiInfoList:
    - snssai:
        sst: 1
        sd: '000001'
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 2
        sd: '000001'
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 3
        sd: '000001'
      nsiInformationList:
        nrfId: http://192.168.70.137:8080/nnrf-disc/v1/nf-instances
        nsiId: '12'
  taInfoList:
    - tai:
        plmnId:
          mcc: '208'
          mnc: '95'
        tac: '33456'
      supportedSnssaiList:
       - sst: 1
         sd: "000001"
       - sst: 2
         sd: "000001"
       - sst: 3
         sd: "000001"
  amfInfoList:
    - targetAmfSet: oai5gcn.mcc208.mnc95.regionid128.setid1.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances'
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 208
                  mnc: 95
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                  sd: "000001"
                - sst: 2
                  sd: "000001"
                - sst: 3
                  sd: "000001"